version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Update known hosts
          command: mkdir ~/.ssh; touch ~/.ssh/known_hosts; ssh-keyscan $SSH_HOST > ~/.ssh/known_hosts
      - checkout
      - run:
          name: 'Deploy Over SSH'
          command: ssh $SSH_USER@$SSH_HOST "source .profile; cd ECommerce-BND; bash scripts/deploy.sh"

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
